#!/usr/bin/env bash


brew install SDL

python3 -m pip install PIP SetUpTools --upgrade --user

python3 -m pip install -r requirements.txt --upgrade --user
python3 -m pip install -r requirements-Mac.txt --upgrade --user
