#!/usr/bin/env bash


brew install SDL
brew upgrade SDL

python3 -m pip install PIP SetUpTools --upgrade

python3 -m pip install -r requirements.txt --no-cache-dir --upgrade --user
python3 -m pip install -r requirements-Mac.txt --no-cache-dir --upgrade --user
