#!/usr/bin/env bash


apt update
apt install --yes llibasound2-dev ibbluetooth-dev

python3 -m pip install pip --upgrade --user

python3 -m pip install -r requirements.txt --upgrade --user --use-feature=2020-resolver
python3 -m pip install -r requirements-Linux.txt --upgrade --user --use-feature=2020-resolver
