#!/usr/bin/env bash


python3 -m pip install pip --upgrade --user

python3 -m pip install -r requirements.txt --upgrade --user --use-feature=2020-resolver
python3 -m pip install -r requirements-Win.txt --upgrade --user --use-feature=2020-resolver
