#!/usr/bin/env bash


python -m pip install PIP SetUpTools --upgrade --user

python -m pip install -r requirements.txt --no-cache-dir  --upgrade --user
python -m pip install -r requirements-Win.txt --no-cache-dir --upgrade --user
