#!/usr/bin/env bash


apt update
apt install --yes libasound2-dev libbluetooth-dev

python3 -m pip install PIP SetUpTools --upgrade

python3 -m pip install -r requirements.txt --upgrade --user
python3 -m pip install -r requirements-Linux.txt --upgrade --user
