ev3.move(forSeconds: 1, left Port: .b, rightPort: .c, leftPower: 50, rightPower: 50)
ev3.move(for Rotations: 1.5, left Port: .b, rightPort: .c, leftPower: -70, rightPower: -30)
ev3.move(for Rotations: 1.5, left Port: .b, rightPort: .c, leftPower: -30, rightPower: -70)
ev3.move(for Rotations: 0.5, left Port: .b, rightPort: .c, leftPower: -50, rightPower: -50)
ev3.move(for Rotations: 1, left Port: .b, rightPort: .c, leftPower: 50, rightPower: 50)
